apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
    version: 1

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: clickhouse
      username: default
      tlsSkipVerify: false
      secure: false
      protocol: native
    secureJsonData:
      password: default
