services:
  app:
    image: $WORKSPACE_NAME/fpm:latest
    build:
      context: $TPL_PATH/php
      args:
        - USER_ID=$USER_ID
        - GROUP_ID=$GROUP_ID
    hostname: "$APP_NAME.$BASE_DOMAIN"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "80"
      HOME: /tmp/home
      COMPOSER_HOME: /tmp/home/composer
      COMPOSER_CACHE_DIR: /tmp/home/composer_cache
    working_dir: /var/www
    entrypoint:
      - "/usr/local/bin/entrypoint"
    volumes:
      - "$SVC_PATH:/var/www"
      - "$HOME_PATH:/tmp/home"
      - "$HOME_PATH/.npm:/.npm"
      - "$HOME_PATH/.config:/.config"
      - "$TPL_PATH/php/entrypoint:/usr/local/bin/entrypoint"
      - "$TPL_PATH/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    networks:
      - dev
  nginx:
    image: $NGINX_IMAGE
    volumes:
      - "$SVC_PATH:/var/www"
      - "$TPL_PATH/nginx/default.conf.template:/etc/nginx/conf.d/default.conf"
    network_mode: "service:app"
    depends_on:
      - app

networks:
  dev:
    external: true
    name: $NETWORK
